"""Neural network building blocks — modules, losses, initializers, and optimizers.

All primary symbols are importable directly from ``neuralogic.nn``::

    from neuralogic.nn import GCNConv, LSTM, MSE, Uniform, Adam
"""

from neuralogic.nn.init import (
    Constant,
    Glorot,
    He,
    Initializer,
    Longtail,
    Normal,
    Uniform,
)
from neuralogic.nn.loss import (
    MSE,
    CrossEntropy,
    ErrorFunction,
    SoftEntropy,
)
from neuralogic.nn.module import (
    GRU,
    LSTM,
    MLP,
    RNN,
    APPNPConv,
    Attention,
    AvgPooling,
    GATv2Conv,
    GCNConv,
    GENConv,
    GINConv,
    GINEConv,
    Linear,
    MAGNNLinear,
    MAGNNMean,
    MaxPooling,
    MetaConv,
    Module,
    MultiheadAttention,
    Pooling,
    PositionalEncoding,
    ResGatedGraphConv,
    RGCNConv,
    RvNN,
    SAGEConv,
    SGConv,
    SumPooling,
    TAGConv,
    Transformer,
    TransformerDecoder,
    TransformerEncoder,
)
from neuralogic.nn.optim import (
    SGD,
    Adam,
    Optimizer,
)
from neuralogic.nn.trainer import (
    CheckpointCallback,
    EarlyStoppingCallback,
    Metric,
    ProgressCallback,
    Trainer,
    TrainerCallback,
    TrainerHistory,
    compute_metrics,
)

__all__ = [
    # modules
    "APPNPConv",
    "Attention",
    "AvgPooling",
    "GATv2Conv",
    "GCNConv",
    "GENConv",
    "GINConv",
    "GINEConv",
    "GRU",
    "Linear",
    "LSTM",
    "MAGNNLinear",
    "MAGNNMean",
    "MaxPooling",
    "MetaConv",
    "MLP",
    "Module",
    "MultiheadAttention",
    "Pooling",
    "PositionalEncoding",
    "ResGatedGraphConv",
    "RGCNConv",
    "RNN",
    "RvNN",
    "SGConv",
    "SAGEConv",
    "SumPooling",
    "TAGConv",
    "Transformer",
    "TransformerDecoder",
    "TransformerEncoder",
    # losses
    "MSE",
    "CrossEntropy",
    "SoftEntropy",
    "ErrorFunction",
    # initializers
    "Uniform",
    "Normal",
    "Constant",
    "Glorot",
    "He",
    "Longtail",
    "Initializer",
    # optimizers
    "Adam",
    "SGD",
    "Optimizer",
    # trainer
    "Trainer",
    "TrainerHistory",
    "TrainerCallback",
    "EarlyStoppingCallback",
    "CheckpointCallback",
    "ProgressCallback",
    "compute_metrics",
    "Metric",
]
