blank_issues_enabled: true
contact_links:
  - name: 💬 Join discussions
    url: https://github.com/LukasZahradnik/PyNeuraLogic/discussions
    about: Ask questions, answer others' questions or participate in discussions in general.
