
name: Code Quality

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd /home/runner/work/PyNeuraLogic/PyNeuraLogic/
          pip install black==23.11.0
          pip install mypy
          pip install flake8

      - run: black --check neuralogic
      - run: flake8 neuralogic
